name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            icon: icons/1.ico
            name: QB_Cleaner_Windows
            ext: .exe
          - os: ubuntu-latest
            icon: icons/1.png
            name: QB_Cleaner_Linux
            ext: ""
          - os: macos-latest
            icon: icons/1.icns
            name: QB_Cleaner_macOS
            ext: ""

    steps:
      - uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Установка зависимостей
        run: pip install pyinstaller requests

      - name: Сборка
        run: >
          pyinstaller --onefile
          --icon="${{ matrix.icon }}"
          --name "${{ matrix.name }}"
          qb_cleaner.py

      - name: Загрузка артефакта
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: dist/${{ matrix.name }}${{ matrix.ext }}
